name: cabi-env
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - statsmodels[version='>=0.12']
  - seaborn
  - sqlalchemy
  - geopandas
  - numpy
  - psycopg2
  - shapely
  - jupyterlab
  - scipy
  - contextily
  - geoalchemy2
  - scikit-learn
  - pandas
