name: cabi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-build
  - joblib>=0.11
  - Cython>=0.29, <0.29.18
  - matplotlib
  - statsmodels[version='>=0.12']
  - seaborn
  - sqlalchemy
  - geopandas
  - numpy>=1.17.3
  - psycopg2
  - shapely
  - jupyterlab
  - scipy
  - contextily
  - geoalchemy2
  - scikit-learn
  - pandas
